"""Added Admin model

Revision ID: c877a99f6af4
Revises: 8a7877fd3b09
Create Date: 2020-07-16 13:31:21.707730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c877a99f6af4'
down_revision = '8a7877fd3b09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('first_name', sa.String(
                        length=100), nullable=True),
                    sa.Column('last_name', sa.String(
                        length=100), nullable=True),
                    sa.Column('login', sa.String(length=80), nullable=True),
                    sa.Column('email', sa.String(length=120), nullable=True),
                    sa.Column('password', sa.String(length=94), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('login')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admins')
    # ### end Alembic commands ###
